//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelatorioApp.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RelatorioApp.i18n.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochuras:.
        /// </summary>
        public static string main_brochuras {
            get {
                return ResourceManager.GetString("main_brochuras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudos Diferentes:.
        /// </summary>
        public static string main_estudos {
            get {
                return ResourceManager.GetString("main_estudos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltam para acabar:.
        /// </summary>
        public static string main_faltamAcabar {
            get {
                return ResourceManager.GetString("main_faltamAcabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folhetos:.
        /// </summary>
        public static string main_folhetos {
            get {
                return ResourceManager.GetString("main_folhetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas:.
        /// </summary>
        public static string main_horas {
            get {
                return ResourceManager.GetString("main_horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livros:.
        /// </summary>
        public static string main_livros {
            get {
                return ResourceManager.GetString("main_livros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meu alvo é:.
        /// </summary>
        public static string main_meuAlvo {
            get {
                return ResourceManager.GetString("main_meuAlvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to por dia.
        /// </summary>
        public static string main_porDia {
            get {
                return ResourceManager.GetString("main_porDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preciso de .
        /// </summary>
        public static string main_precisoDe {
            get {
                return ResourceManager.GetString("main_precisoDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev. Avul:.
        /// </summary>
        public static string main_revAvul {
            get {
                return ResourceManager.GetString("main_revAvul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisitas:.
        /// </summary>
        public static string main_revisitas {
            get {
                return ResourceManager.GetString("main_revisitas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meu Relatorio:.
        /// </summary>
        public static string main_titulo {
            get {
                return ResourceManager.GetString("main_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabalho iniciado:.
        /// </summary>
        public static string main_trabalhoIniciado {
            get {
                return ResourceManager.GetString("main_trabalhoIniciado", resourceCulture);
            }
        }
    }
}
